config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    namespace :questions do
      get 'edit/c2/:id', to: 'edit#c2'
    end
  end

  namespace :admin do
    namespace :questions do
      get 'edit/c3/:id', to: 'edit#c3'
    end
  end

  namespace :admin do
    namespace :questions do
      get 'edit/c4/:id', to: 'edit#c4'
    end
  end

  namespace :admin do
    namespace :questions do
      get 'edit/c5/:id', to: 'edit#c5'
    end
  end

  namespace :admin do
    namespace :questions do
      get 'new/c2'
    end
  end

  namespace :admin do
    namespace :questions do
      get 'new/c3'
    end
  end

  namespace :admin do
    namespace :questions do
      get 'new/c4'
    end
  end

  namespace :admin do
    namespace :questions do
      get 'new/c5'
    end
  end

  namespace :admin do
    namespace :questions do
      post 'new/show'
    end
  end
  
  namespace :admin do
    patch 'questions/update'
  end
  
  namespace :admin do
    post 'questions/create'
  end
  
  namespace :admin do
    get 'questions/show'
  end

  namespace :admin do
    get 'questions/edit/:id', to: 'questions#edit'
  end
  
  namespace :admin do
    delete 'questions/delete/:id', to: 'questions#delete'
  end

  namespace :admin do
    get 'questions/new'
  end
  
  namespace :admin do
    put 'questions/copy/:id', to: 'questions#copy'
  end
  
  get 'students/logout'
  
  #GET
  get 'welcome/show'
  
  get 'admin/login'
  get 'admin/show'
  get 'admin/logout'
  get 'admin/export'
  
  get 'students/welcome'
  get 'students/register'
  get 'students/logout'
  get 'students/show'
  
  get 'admin/questions/show'
  
  get 'questions/edit'
  get 'questions/remove'
  
  #POST
  post 'students/welcome'

  post 'admin/delete'
  post 'admin/update'
  
  post 'students/practice', :as => :students_practice
  post 'students/show'
  post 'admin/login'
  post 'admin/show'
  
  match '/questions', to: 'questions#view', via: [:get, :post]
  
  resources :students
  
  resources :questions, only: [:view], via: [:post]
  
  resources :instructions
  
  root to: 'welcome#show'

  
  
  get 'about', to: 'about#show'
  get 'admin', to: 'admin#show'
  get 'admin/evaluations', to: 'evaluations#show'
  post 'admin/evaluations', to: 'evaluations#show'
  get 'admin/evaluations/view/:id', to: 'evaluations#view'
  delete 'admin/evaluations/delete/:id', to: 'evaluations#delete'
  # '/' Route
  get 'welcome/show'
  get 'students/hello'

  post 'admin/evaluations/new' => 'evaluations#create', :as => :create
  #post 'admin/evaluations' => 'evaluations#update_instructions', :as => :update_instructions
  post 'admin/evaluations/selectr' => 'evaluations#selectr', :as => :selectr_evaluation
  get 'admin/evaluations/selectr' => 'evaluations#selectr', :as => :selectr_evaluation_get
  get 'admin/evaluations/new' => 'evaluations#new', :as => :new_evaluation
  get 'questions/instructions' => 'students#instructions', :as => :instructions_student
  get 'questions/save' => 'questions#save', :as => :save_test
  patch 'admin/evaluations' => 'evaluations#update_instructions', :as => :update_instructions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'admin/export' => 'admin#export', :as => :export_admin
  get 'admin/questions/export' => 'admin#export_questions', :as => :export_questions
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
    validates_uniqueness_of :eid
    attr_accessor :avg_score
    attr_accessor :max_score
    attr_accessor :min_score
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
    def show
        if(session[:admin] != "login")
          redirect_to controller: 'admin', action: 'login'
        end

        @instructions = Instruction.all.first
        session[:content]=[]
        session[:title]=""
        @allevaluations=Evaluation.all.order('eid asc')
        
        #update evaluation access_code
        if(!params[:access_code].nil? and !params[:eid].nil?)
            if(check_access_code_uniqueness(params[:access_code]) == true)
              update(params[:access_code], params[:eid]) 
            else
              flash[:warning] = "Access code already exists for another evaluation!"
              redirect_to controller: 'evaluations', action: 'show'
            end
        end
    end
    
    def new
        if(session[:admin] != "login")
          redirect_to controller: 'admin', action: 'login'
        end
        
        logger.info "new"
        logger.info session[:content]
        @questions=Question.all.order(:qid)
        @selected_questions=[]
        if session[:title]==nil then session[:title]="" end
    end
    
    def create
        # flash[:error]=""
        if params[:commit]!=nil&&params[:commit]=="Random"&&params[:size]!=""
            if params[:title]!=nil&&params[:title]!=""
                session[:title]=params[:title]
            end
            puts session[:title]
            redirect_to selectr_evaluation_path("size":params[:size].to_i)
        else
            logger.info "create"
            if(params[:title]!=nil&&params[:title]!=""&&params[:questions]!=nil)
                scales=[]
                if params[:scales]!=nil
                    params[:scales].each do |k,v|
                        if params[:questions][k.split(",")[0]]!=nil
                           scales << v.to_i 
                        end
                    end
                end
                #puts scales
                @question=Evaluation.create!(:eid =>(Evaluation.maximum(:eid)==nil) ? 1 : Evaluation.maximum(:eid)+1,:title =>params[:title],:content =>params[:questions].values, :scales=> scales, :qids=> params[:questions].keys.map(&:to_i))
                flash[:success] = "Evaluation #{@question.title} was successfully created."
                redirect_to action: "show"
            else
                flash[:warning] = "Some parameter is missing."
                session[:content]=[]
                if params[:questions]!=nil
                    params[:questions].keys.each do |q|
                        session[:content] << q.to_i
                    end
                end
                redirect_to new_evaluation_path
            end
            #session[:content]=[]
            
        end
        
    end
    
    def update_instructions
        @instructions = Instruction.all.first
        @instructions.content = params[:content]
        @instructions.save
        flash[:success] = "Instruction updated!"
        redirect_to controller: 'evaluations', action: 'show'
    end
    
    def selectr
        logger.info "selectr"
        session[:content]=[]
        already_seen = []
        size=3
        if(params[:size]!=nil)
            size=params[:size].to_i
        end
        
        while already_seen.length<size do 
            if already_seen == []
                id = Question.order('RANDOM()').pluck(:qid).first
                already_seen << id
            else
                id = Question.order('RANDOM()').where.not(qid: already_seen).pluck(:qid).first
                already_seen << id
            end
        end
        already_seen.each do |q|
            session[:content] << q
        end
        puts session[:content]
        
        redirect_to new_evaluation_path
    end
    
    def check_access_code_uniqueness code
      @evaluation = Evaluation.where(access_code: code)
      if(@evaluation.size == 0)
          return true
      else
          return false
      end
    end
    def edit
    
    end
    
    def update access_code, eid
       @evaluation = Evaluation.where(eid: params[:eid].keys[0]).first
       @evaluation.access_code = access_code
       @evaluation.save
       redirect_to controller: 'evaluations', action: 'show'
    end
    
    def destroy
    
    end
    def view
        eid = params[:id]
        @evaluation = Evaluation.where(eid: eid)[0]
        # puts @evaluation.content
        evalQuestions = []
        @evaluation.content.each do |question|
            evalQuestions << question
        end
        @questions = Question.where(:content => evalQuestions)
    end
    
    def delete
        evaluation = Evaluation.where(eid: params[:id])
        if evaluation.count == 0
            flash[:warning] = "Unable to find evaluation. Please try again."
            redirect_to controller: 'evaluations', action: 'show'
        else
            @evaluation = evaluation[0]
            @evaluation.delete
            flash[:success] = "Evaluation #{@evaluation.eid} successfully deleted."
            redirect_to controller: 'evaluations', action: 'show'
        end
    end
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/views/evaluations/_form.html.erb
<%= form_with(model: evaluation, local: true) do |form| %>
  <% if evaluation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(evaluation.errors.count, "error") %> prohibited this evaluation from being saved:</h2>

      <ul>
      <% evaluation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/evaluations/edit.html.erb
<h1>Editing Evaluation</h1>

<%= render 'form', evaluation: @evaluation %>

<%= link_to 'Show', @evaluation %> |
<%= link_to 'Back', evaluations_path %>

app/views/evaluations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Evaluations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @evaluations.each do |evaluation| %>
      <tr>
        <td><%= link_to 'Show', evaluation %></td>
        <td><%= link_to 'Edit', edit_evaluation_path(evaluation) %></td>
        <td><%= link_to 'Destroy', evaluation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evaluation', new_evaluation_path %>

app/views/evaluations/new.html.erb
<div class="row">
	<div class="col-sm-12">
		<h1>Enter the new evaluation</h1>
		<p>Check next to each question to enable that question for the new evaluation. Select from the scale option for each answer to adjust the number of points each answer is worth.</p>
		<% flash.each do |key, value|%>
		    <div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
	</div>
	<div class="col-sm-12">
		<%=form_for :evaluation, :url => {:controller => 'evaluations',:action => "create"} do |e|%>
	
			<div class="form-group">
				<%= label :title_label, 'Title: '%>
				<%= text_field_tag :title, session[:title]%>
			</div>
			
			<div class="form-group">
				<%= label :random_label, 'How many random questions do you want?'%>
				<%= number_field_tag :size %>
				<%= submit_tag 'Random',:id=>"evaluations_random", :class => "btn btn-primary" %>
			</div>
		
			<% @questions.each do |question| %>
				<div class="form-group">
					<h3><%= check_box_tag "questions[#{question.qid}]",question.content,(session[:content]!=nil&&session[:content].include?(question.qid)), :multiple=> true %>
					Question:
				    <%= question.qid %></h3>
			    </div>
			    <div class="form-group">
			    	<%= text_area_tag :question_content, question.content, :rows => 5, :cols => 60, :disabled => true %>
			    </div>
			    <div class="form-group">
				    <% if question.c1!=nil&&question.c1!="" %>
				    	<label>Scale: </label>
				    	<%= select_tag("scales[#{question.qid},1]", options_for_select([['0', 0], ['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5]]), :id =>"scales#{question.qid}-1")%>
				    	<%= text_area_tag :question_c1, question.c1, :rows => 5, :cols => 60, :disabled => true %>
				    	<%= simple_format " \n " %>
				    <% end %>
			    </div>
			    <div class="form-group">
				   	<% if question.c2!=nil&&question.c2!="" %>
				    	<label>Scale: </label>
				    	<%= select_tag("scales[#{question.qid},2]", options_for_select([['0', 0], ['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5]]), :id => "scales#{question.qid}-2") %>
				    	<%= text_area_tag :question_c2, question.c2, :rows => 5, :cols => 60, :disabled => true %>
				    	<%= simple_format " \n " %>
				    <% end %>
			    </div>
			    <div class="form-group">
				    <% if question.c3!=nil&&question.c3!="" %>
				    	<label>Scale: </label>
				    	<%= select_tag("scales[#{question.qid},3]", options_for_select([['0', 0], ['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5]]), :id => "scales#{question.qid}-3") %>
				    	<%= text_area_tag :question_c3, question.c3, :rows => 5, :cols => 60, :disabled => true %>
				    	<%= simple_format " \n " %>
				    <% end %>
			    </div>
			    <div class="form-group">
				    <% if question.c4!=nil&&question.c4!="" %>
				    	<label>Scale: </label>
				    	<%= select_tag("scales[#{question.qid},4]", options_for_select([['0', 0], ['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5]]), :id => "scales#{question.qid}-4") %>
				    	<%= text_area_tag :question_c4, question.c4, :rows => 5, :cols => 60, :disabled => true %>
				    	<%= simple_format " \n " %>
				    <% end %>
			    </div>
			    <div class="form-group">
				    <% if question.c5!=nil&&question.c5!="" %>
				    	<label>Scale: </label>
				    	<%= select_tag("scales[#{question.qid},5]", options_for_select([['0', 0], ['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5]]), :id => "scales#{question.qid}-5") %>
				    	<%= text_area_tag :question_c5, question.c5, :rows => 5, :cols => 60, :disabled => true %>
				    	<%= simple_format " \n " %>
				    <% end %>
			    </div>
			    <hr>
			<% end %>
			<div class="form-group">
				<%= submit_tag 'Save Changes',:id=>"evaluations_submit", :class => "btn btn-primary" %>
			</div>
		<% end %>
	</div>
</div>

<%= tinymce %>

<script type="text/javascript">
  tinyMCE.init({
    selector: 'textarea',
    branding: false,
    menubar: false,
    toolbar: false,
    readonly: 1,
  });
</script>

app/views/evaluations/selectr.html.erb
<%=form_tag evaluations_path do %>
    <%= submit_tag 'Save Changes' %>
<% end %>

app/views/evaluations/show.html.erb
<div class="row">
    <div class="col-sm-12">
        <h1>Evaluation Manager</h1>
        <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <h3>Current Evaluations:</h3>
        <div class="table-responsive">
            <table class="table table-bordered table-hover">
                <thead class="thead-light">
                    <tr>
                        <th>ID</th>
                        <th>Title</th>
                        <th>QuestionIDs</th>
                        <th>Access Code</th>
                        <th>Change Access Code</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    <% @allevaluations.each do |evaluation| %>
                      <tr>
                        <td><%= link_to evaluation.eid, "/admin/evaluations/view/#{evaluation.eid}" %></td>
                        <td><%= evaluation.title %></td>
                        <td><%= evaluation.qids %></td>
                        <td><%= evaluation.access_code %></td>
                        <td><%= form_tag do %>
                            <%= text_field_tag :access_code %>
                            <%= submit_tag "Update", :name => "eid[#{evaluation.eid}]", class: "btn btn-primary btn-sm" %><br>
                            <% end %>
                        </td>
                        <td><%= link_to 'Remove', "/admin/evaluations/delete/#{evaluation.eid}", :method => :delete %></td>
                      </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-sm-12">
        <%= link_to 'Add new evaluation', new_evaluation_path, :class=>"btn btn-primary btn-lg" %>
    </div>
    <div class="col-sm-12">
        <h3>Instructions for Evaluations:</h3>
        <%= form_for @instructions, :url => {:action => "update_instructions"} do |f| %>
            <div class="margin-bottom">
                <%= text_area_tag :content, @instructions.content, :class => "tinymce", :rows => 10, :cols => 120 %>
                <%= tinymce %>
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-lg" type="submit">Update Instructions</button>
            </div>
        <% end %>
    </div>
</div>

app/views/evaluations/showeval.html.erb
<h1>Evaluations In database</h1>
<table id="evaluations">
    <thead>
        <tr>
            <th># &nbsp; &nbsp; &nbsp;</th>
            <th>Title &nbsp; &nbsp; &nbsp;</th>
            <th>Content &nbsp; &nbsp; &nbsp;</th>
        </tr>
    </thead>
  
    <tbody>
        <% @allevaluations.each do |evaluation| %>
          <tr>
            <td><%= evaluation.eid %></td>
            <td><%= evaluation.title %></td>
            <td><%= evaluation.content %></td>
          </tr>
        <% end %>
    </tbody>
</table>
<li><%= link_to 'Add new evaluation', new_evaluation_path %></li>

app/views/evaluations/view.html.erb
<%= form_for @evaluation, :url => {:action => "view"} do |f| %>
    <h1>Evaluation <%= @evaluation.eid %>: <%= @evaluation.title %></h1>
    <%= hidden_field_tag :eid, @evaluation.eid %>
    <% counter=0 %>
    <% @questions.each_with_index do |question, index|%>
        <h2>Question
            <%= "#{index+1}: " %>
        </h2>
        <%= text_area_tag :question_content, question.content, :rows => 5, :cols => 120, :disabled => true %>
        <%= simple_format " \n " %>
        
        <h4> Answer Choice 1 <%= "(#{@evaluation.scales[counter]} points)"%>: </h4>
        <%= text_area_tag :choice1, question.c1%>
        <%= simple_format " \n " %>
        <% counter+=1 %>
        
        <h4> Answer Choice 2 <%= "(#{@evaluation.scales[counter]} points)"%>: </h4>
        <%= text_area_tag :choice2, question.c2 %>
        <%= simple_format " \n " %>
        <% counter+=1 %>
        
        <% if question.numAnswers == 3 %>
            <h4> Answer Choice 3 <%= "(#{@evaluation.scales[counter]} points)"%>: </h4>
            <%= text_area_tag :choice3, question.c3 %>
            <%= simple_format " \n " %>
            <% counter+=1 %>
        <% elsif question.numAnswers == 4 %>
            <h4> Answer Choice 3 <%= "(#{@evaluation.scales[counter]} points)"%>: </h4>
            <%= text_area_tag :choice3, question.c3 %>
            <%= simple_format " \n " %>
            <% counter+=1 %>
            <h4> Answer Choice 4 <%= "(#{@evaluation.scales[counter]} points)"%>: </h4>
            <%= text_area_tag :choice4,question.c4 %>
            <%= simple_format " \n " %>
            <% counter+=1 %>
        <% elsif question.numAnswers == 5 %>
            <h4> Answer Choice 3 <%= "(#{@evaluation.scales[counter]} points)"%>: </h4>
            <%= text_area_tag :choice3, question.c3 %>
            <%= simple_format " \n " %>
            <% counter+=1 %>
            <h4> Answer Choice 4 <%= "(#{@evaluation.scales[counter]} points)"%>: </h4>
            <%= text_area_tag :choice4,question.c4 %>
            <%= simple_format " \n " %>
            <% counter+=1 %>
            <h4> Answer Choice 5 <%= "(#{@evaluation.scales[counter]} points)"%>: </h4>
            <%= text_area_tag :choice5,question.c5 %>
            <%= simple_format " \n " %>
            <% counter+=1 %>
        <% end %>
        
        <h4>Correct Answer Choice:</h4>
        <% if question.getCorrectAnswerNum == 1 %>
            <%= text_area_tag :answer, question.c1 %>
        <% elsif question.getCorrectAnswerNum == 2 %>
            <%= text_area_tag :answer, question.c2 %>
        <% elsif question.getCorrectAnswerNum == 3 %>
            <%= text_area_tag :answer, question.c3 %>
        <% elsif question.getCorrectAnswerNum == 4%>
            <%= text_area_tag :answer, question.c4 %>
        <% elsif question.getCorrectAnswerNum == 5 %>
            <%= text_area_tag :answer, question.c5 %>            
        <% end %>
        <br>
    <% end %>
    

<% end %>

<%= tinymce %>
<script type="text/javascript">
  tinyMCE.init({
    selector: 'textarea',
    branding: false,
    menubar: false,
    toolbar: false,
    readonly: 1,
  });
</script>