config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    namespace :questions do
      get 'edit/c2/:id', to: 'edit#c2'
    end
  end

  namespace :admin do
    namespace :questions do
      get 'edit/c3/:id', to: 'edit#c3'
    end
  end

  namespace :admin do
    namespace :questions do
      get 'edit/c4/:id', to: 'edit#c4'
    end
  end

  namespace :admin do
    namespace :questions do
      get 'edit/c5/:id', to: 'edit#c5'
    end
  end

  namespace :admin do
    namespace :questions do
      get 'new/c2'
    end
  end

  namespace :admin do
    namespace :questions do
      get 'new/c3'
    end
  end

  namespace :admin do
    namespace :questions do
      get 'new/c4'
    end
  end

  namespace :admin do
    namespace :questions do
      get 'new/c5'
    end
  end

  namespace :admin do
    namespace :questions do
      post 'new/show'
    end
  end
  
  namespace :admin do
    patch 'questions/update'
  end
  
  namespace :admin do
    post 'questions/create'
  end
  
  namespace :admin do
    get 'questions/show'
  end

  namespace :admin do
    get 'questions/edit/:id', to: 'questions#edit'
  end
  
  namespace :admin do
    delete 'questions/delete/:id', to: 'questions#delete'
  end

  namespace :admin do
    get 'questions/new'
  end
  
  namespace :admin do
    put 'questions/copy/:id', to: 'questions#copy'
  end
  
  get 'students/logout'
  
  #GET
  get 'welcome/show'
  
  get 'admin/login'
  get 'admin/show'
  get 'admin/logout'
  get 'admin/export'
  
  get 'students/welcome'
  get 'students/register'
  get 'students/logout'
  get 'students/show'
  
  get 'admin/questions/show'
  
  get 'questions/edit'
  get 'questions/remove'
  
  #POST
  post 'students/welcome'

  post 'admin/delete'
  post 'admin/update'
  
  post 'students/practice', :as => :students_practice
  post 'students/show'
  post 'admin/login'
  post 'admin/show'
  
  match '/questions', to: 'questions#view', via: [:get, :post]
  
  resources :students
  
  resources :questions, only: [:view], via: [:post]
  
  resources :instructions
  
  root to: 'welcome#show'

  
  
  get 'about', to: 'about#show'
  get 'admin', to: 'admin#show'
  get 'admin/evaluations', to: 'evaluations#show'
  post 'admin/evaluations', to: 'evaluations#show'
  get 'admin/evaluations/view/:id', to: 'evaluations#view'
  delete 'admin/evaluations/delete/:id', to: 'evaluations#delete'
  # '/' Route
  get 'welcome/show'
  get 'students/hello'

  post 'admin/evaluations/new' => 'evaluations#create', :as => :create
  #post 'admin/evaluations' => 'evaluations#update_instructions', :as => :update_instructions
  post 'admin/evaluations/selectr' => 'evaluations#selectr', :as => :selectr_evaluation
  get 'admin/evaluations/selectr' => 'evaluations#selectr', :as => :selectr_evaluation_get
  get 'admin/evaluations/new' => 'evaluations#new', :as => :new_evaluation
  get 'questions/instructions' => 'students#instructions', :as => :instructions_student
  get 'questions/save' => 'questions#save', :as => :save_test
  patch 'admin/evaluations' => 'evaluations#update_instructions', :as => :update_instructions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'admin/export' => 'admin#export', :as => :export_admin
  get 'admin/questions/export' => 'admin#export_questions', :as => :export_questions
end

app/models/student.rb
class Student < ApplicationRecord
    def self.to_csv
        attributes = %w{uin name section attempts score}
        CSV.generate(headers: true) do |csv|
          csv << attributes
          all.each do |student|
            csv << student.attributes.values_at(*attributes)
          end
        end
    end

end

app/controllers/students_controller.rb
require 'net/https'
require 'uri'

class StudentsController < ApplicationController
  
  def register
    @all_students = Student.all
    @student = Student.new
    @sections = Section.all.order('section_number asc')
  end
  
  def welcome
    if(!params[:uin].nil?)
      uin = params[:uin]
      if(login(uin) == true)
        redirect_to controller: 'students', action: 'show'
      else
        redirect_to conntroller: 'students', action: 'welcome'
      end
    end
  end
  
  def instructions
  end
  
  def login(uin)
    #first check if input is legal
    if(uin.to_i > 999999999 || uin.to_i < 100000000)
      flash[:warning] = "Please enter a valid UIN!"
      return false
    end
    
    #then validate
    @student = Student.where(uin: uin.to_i).first
    if(@student.nil?)
      flash[:warning] = "UIN not registered!"
      return false
    else
      #set session key
      session[:uin] = uin
      return true
    end
  end
    
  def show
    if(session[:uin].nil?)
      redirect_to controller: 'students', action: 'welcome'
    end
  
    if(session[:uin].nil?)
      return
    end
    
    @sections = Section.all.order('section_number asc')
    @list_of_sections = Section.pluck(:section_number).sort
    @instructions = Instruction.all.first
    
    @student = Student.where(uin: session[:uin]).first
    if(!params[:access_code].nil?)
      if(params[:access_code] == "")
        flash[:warning] = "Please enter an access code!"
        redirect_to controller: 'students', action: 'show'
      else
        @evaluations = Evaluation.where(access_code: params[:access_code]).first
        if(@evaluations.nil?)
          flash[:warning] = "Error: No evaluation exists with the corresponding access code!"
          redirect_to controller: 'students', action: 'show'
        else
          session[:eid] = @evaluations.eid
          session[:page]=0
          session[:choice]=[]
          @student.choices=[]
          @student.save
          redirect_to controller: 'questions', action: 'view'
        end
      end
    end
    
    #update student section
    if(!params[:section].nil? and !params[:uin].nil?)
      update(params[:uin], params[:section])
    end
  end
  
  def practice 
    if(session[:uin].nil?)
      redirect_to controller: 'students', action: 'welcome'
    end
  
    if(session[:uin].nil?)
      return
    end
    
    @sections = Section.all.order('section_number asc')
    @list_of_sections = Section.pluck(:section_number).sort
    @instructions = Instruction.all.first
    
    @student = Student.where(uin: session[:uin]).first
    @access_code = "practice"
    @evaluations = Evaluation.where(access_code: @access_code).first
    if(@evaluations.nil?)
      flash[:warning] = "Error: No practice evaluation exists. Please create a new one"
      redirect_to controller: 'students', action: 'show'
    else
      session[:eid] = @evaluations.eid
      session[:page]=0
      session[:choice]=[]
      @student.choices=[]
      @student.save
      redirect_to controller: 'questions', action: 'view'
    end
  end 
  
  def update uin,section
    @student = Student.where(uin: params[:uin].keys[0]).first
    @student.section = params[:section]
    @student.save
    flash[:success] = "Section updated"
    redirect_to controller: 'students', action: 'show'
  end
  
  def create
    params.permit! #allow mass assignment
    @student = Student.new(params[:student])
    @student.attempts = 0
    @student.score = -1
    @student.scoretotal=-1
    @student.created_at =  DateTime.now
    res = validate_entry(@student)
    #debugger
    if(res == true)
      if(@student.save)
        redirect_to action: "register"
      end
    else
      redirect_to action: "register"
    end
  end
  
  def validate_entry entry
    puts "validating"
    
    #nil entry
    if(entry.uin.nil? ||entry.name.nil? || entry.section.nil? || entry.name == "")
      flash[:warning] = "Please fill in all required fields!!"
      return false
    end

    
    #inavlid uin
    if(entry.uin > 999999999 || entry.uin < 100000000)
      flash[:warning] = "Invalid UIN!"
      return false
    end
    
    #uin uniqueness
    ret = Student.where(uin: entry.uin)
    if !ret.empty?
      flash[:warning] = "UIN already exist!"
      return false
    end
    
    flash[:success] = "Student Added!"
    return true
  end
  
  def logout
    session[:uin] = nil
    flash[:success] = "Successful logged out"
    redirect_to controller: 'students', action: 'welcome'
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/hello.html.erb
<h1>Students#hello</h1>
<p>
    <div>Find me in app/views/students/hello.html.erb</div>
    
    <%= form_for @student do |f| %>
      <%= f.label :uin, 'UIN' %><%= f.number_field :uin %><br>
      <%= f.label :name, 'Name' %><%= f.text_field :name %><br>
      <%= f.label :section, 'Section' %><%= f.number_field :section %><br>
      <%= f.submit %>
    <% end %>
    
    <% if flash[:notice] %>
        <div class="notice" style="color: red"><%= flash[:notice] %></div>
    <% end %>
    
    <%= link_to "HomePage", controller: "welcome", action: "show" %>
    
    <table>
        <tr>
            <th>UIN</th>
            <th>Name</th>
            <th>Section</th>
            <th>Attempts</th>
            <th>Score</th>
            <th>Last Start</th>
            <th>Last End</th>
        </tr>
        <% #debugger %>
        <% @all_students.each do |student| %>
            <tr>
                <td><%= student.uin %></td>
                <td><%= student.name %></td>
                <td><%= student.section %></td>
                <td><%= student.attempts %></td>
                <td><%= student.score %></td>
                <td><%= student.last_start %></td>
                <td><%= student.last_end %></td>
            </tr>
        <% end %>
    </table>
</p>

app/views/students/index.html.erb
<h1>All students</h1>

<%= button_to "Display all", {:controller => "students", :action => "index", :display_all => 1}, :method => :post %>

<table id="t01", class="table table-hover">
    <thead>
        <tr>
            <th>Check</th>
            <th>UIN </th>
            <th>Student Name </th>
            <th>Section </th>
            <th>Attempts </th>
            <th>Score </th>
        </tr>
    </thead>
  
    <tbody>
    <%= form_tag students_path, controller: 'student',action: 'index',  method: :post do %>
    <%#=form_for :export_form, :url => {:controller => 'admin',:action => "index"} do |q|%>
         <%# Student.new.attributes.keys[0...Student.new.attributes.keys.length-1].each_with_index do |student, index| %>
        <% @students.each do |student| %>
          <tr>
            <td><%= check_box_tag "student_ids[]", student.id, checked = true %></td>
            <td><%= student.uin%></td>
            <td><%= student.name %></td>
            <td><%= student.section %></td>
            <td><%= student.attempts %></td>
            <td><%= student.score %></td>
          </tr>
        <% end %>
        <%#= submit_tag 'Export to CSV',:id=>"export_to_csv"%>
        <%= submit_tag 'Update', controller: 'students', action: "index" %>
    <% end %>
    </tbody>
</table>
<%= button_to 'Export to CSV', students_path(format: 'csv') %>

app/views/students/register.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>Student Register</h1>
    <p>Register for an account to take your assessment. All scores will automatically be sent to the professors.</p>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  </div>
  <div class="col-sm-12">
      <%= form_for @student do |f| %>
        <%= f.label :uin, 'UIN: ' %><%= f.number_field :uin %><br>
        <%= f.label :name, 'Name: ' %><%= f.text_field :name %><br>
        <%= f.label :section, 'Section: ' %><%= f.select "section", options_from_collection_for_select(@sections, "section_number", "section_number")  %><br>
        <%= f.submit "Create Student", :class => "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/students/show.html.erb
<div class="row">
    <div class="col-sm-12">
        <h1>Student Information</h1>
        <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
    </div>
    <div class="col-sm-12">
        <div class="table-responsive">
            <table class="table table-bordered table-hover">
                <thead class="thead-light">
                    <tr>
                        <th>UIN</th>
                        <th>Name</th>
                        <th>Section</th>
                        <th>Attempts</th>
                        <th>Score</th>
                        <th>Change Section</th>
                    </tr>
                </thead>
                <tbody>
                  <tr>
                    <td><%= @student.uin %></td>
                    <td><%= @student.name %></td>
                    <td><%= @student.section %></td>
                    <td><%= @student.attempts %></td>
                    <td><%= @student.score.to_s+"/"+@student.scoretotal.to_s+"(#{((@student.score+0.0)/((@student.scoretotal.nonzero?||1)+0.0)).round(2)})" %></td>
                    <td><%= form_tag do %>
                        <%= select_tag 'section', options_for_select(@list_of_sections, @selected_section) %>
                        <%= submit_tag "Update", :name => "uin[#{@student.uin}]", class: "btn btn-primary btn-sm" %>
                        <% end %>
                    </td>
                </tr>  
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <h1>Exam Instructions</h1>
        <%= text_area_tag :content, @instructions.content, :rows => 10, :cols => 120%>
        <%= simple_format " \n " %>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <h1>Begin Test</h1>
        <p>In order to take the evaluation, the instructor will provide you an access code. Once you obtain the access code, enter it below and press begin.</p>
    </div>
    <div class="col-sm-12">
        <%= form_tag do%>
            <label for="access_code">Access Code: </label>
            <%= text_field_tag :access_code %><br>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Begin</button>
            </div>
        <% end %>
        <%= button_to 'Practice', students_practice_path, :method => :post, :class => 'btn btn-primary' %>
    </div>
</div>

<%= tinymce %>

<script type="text/javascript">
  tinyMCE.init({
    selector: 'textarea',
    branding: false,
    menubar: false,
    toolbar: false,
    readonly: 1,
  });
</script>

app/views/students/welcome.html.erb
<div class="row">
 <div class="col-sm-12">
  <h1>Student Login</h1>
   <div>
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  </div>
 </div>
 <div class="col-sm-12">
  <%= form_tag do%>
  <div class="form-group">
   <label for="uin">UIN:</label>
    <%= number_field_tag :uin %><br>
  </div>
  <div class="form-group">
   <button class="btn btn-primary" type="submit">Login</button>
   <a href="/students/register" class="btn btn-primary">Register</a>
  </div>
  <% end %>
 </div>
</div>