config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    namespace :questions do
      get 'edit/c2/:id', to: 'edit#c2'
    end
  end

  namespace :admin do
    namespace :questions do
      get 'edit/c3/:id', to: 'edit#c3'
    end
  end

  namespace :admin do
    namespace :questions do
      get 'edit/c4/:id', to: 'edit#c4'
    end
  end

  namespace :admin do
    namespace :questions do
      get 'edit/c5/:id', to: 'edit#c5'
    end
  end

  namespace :admin do
    namespace :questions do
      get 'new/c2'
    end
  end

  namespace :admin do
    namespace :questions do
      get 'new/c3'
    end
  end

  namespace :admin do
    namespace :questions do
      get 'new/c4'
    end
  end

  namespace :admin do
    namespace :questions do
      get 'new/c5'
    end
  end

  namespace :admin do
    namespace :questions do
      post 'new/show'
    end
  end
  
  namespace :admin do
    patch 'questions/update'
  end
  
  namespace :admin do
    post 'questions/create'
  end
  
  namespace :admin do
    get 'questions/show'
  end

  namespace :admin do
    get 'questions/edit/:id', to: 'questions#edit'
  end
  
  namespace :admin do
    delete 'questions/delete/:id', to: 'questions#delete'
  end

  namespace :admin do
    get 'questions/new'
  end
  
  namespace :admin do
    put 'questions/copy/:id', to: 'questions#copy'
  end
  
  get 'students/logout'
  
  #GET
  get 'welcome/show'
  
  get 'admin/login'
  get 'admin/show'
  get 'admin/logout'
  get 'admin/export'
  
  get 'students/welcome'
  get 'students/register'
  get 'students/logout'
  get 'students/show'
  
  get 'admin/questions/show'
  
  get 'questions/edit'
  get 'questions/remove'
  
  #POST
  post 'students/welcome'

  post 'admin/delete'
  post 'admin/update'
  
  post 'students/practice', :as => :students_practice
  post 'students/show'
  post 'admin/login'
  post 'admin/show'
  
  match '/questions', to: 'questions#view', via: [:get, :post]
  
  resources :students
  
  resources :questions, only: [:view], via: [:post]
  
  resources :instructions
  
  root to: 'welcome#show'

  
  
  get 'about', to: 'about#show'
  get 'admin', to: 'admin#show'
  get 'admin/evaluations', to: 'evaluations#show'
  post 'admin/evaluations', to: 'evaluations#show'
  get 'admin/evaluations/view/:id', to: 'evaluations#view'
  delete 'admin/evaluations/delete/:id', to: 'evaluations#delete'
  # '/' Route
  get 'welcome/show'
  get 'students/hello'

  post 'admin/evaluations/new' => 'evaluations#create', :as => :create
  #post 'admin/evaluations' => 'evaluations#update_instructions', :as => :update_instructions
  post 'admin/evaluations/selectr' => 'evaluations#selectr', :as => :selectr_evaluation
  get 'admin/evaluations/selectr' => 'evaluations#selectr', :as => :selectr_evaluation_get
  get 'admin/evaluations/new' => 'evaluations#new', :as => :new_evaluation
  get 'questions/instructions' => 'students#instructions', :as => :instructions_student
  get 'questions/save' => 'questions#save', :as => :save_test
  patch 'admin/evaluations' => 'evaluations#update_instructions', :as => :update_instructions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'admin/export' => 'admin#export', :as => :export_admin
  get 'admin/questions/export' => 'admin#export_questions', :as => :export_questions
end

app/views/admin/export.html.erb
<div class="row">
    <div class="col-sm-12">
        <h1>Student Data Export</h1>
        <p>Export student data including UIN, Name, Section, Attempts, and Scores to a CSV.</p>
        <%= button_to "Display all", {:controller => "admin", :action => "export", :display_all => 1}, :method => :post, :class => "btn btn-primary" %>
        <%= form_tag export_admin_path, controller: 'admin',action: 'export',  method: :post do %>
            <div class="form-group">
            </div>
            <table class="table table-bordered table-hover">
                <thead class="thead-light">
                    <tr>
                        <th>Check</th>
                        <th>UIN </th>
                        <th>Student Name </th>
                        <th>Section </th>
                        <th>Attempts </th>
                        <th>Score </th>
                    </tr>
                </thead>
                <tbody>
                    <% @students.each do |student| %>
                      <tr>
                        <td><%= check_box_tag "student_ids[]", student.id, checked = true %></td>
                        <td><%= student.uin%></td>
                        <td><%= student.name %></td>
                        <td><%= student.section %></td>
                        <td><%= student.attempts %></td>
                        <td><%= student.score %></td>
                      </tr>
                    <% end %>
                </tbody>
            </table>
            <div class="form-group">
                <%= submit_tag 'Update', controller: 'admin', action: "export", class: "btn btn-primary" %>
            </div>
        <% end %>
        <%= button_to 'Export to CSV', export_admin_path(format: 'csv'), class: "btn btn-primary btn-lg" %>

    </div>
</div>

app/views/admin/login.html.erb
<div class="row">
    <div class="col-sm-12">
        <h1>Admin Login</h1>
        <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
    </div>
    <div class="col-sm-12">
        <%= form_tag do%>
            <div class="form-group">
                <label for="key">Key: </label>
                <%= password_field_tag :key %>
            </div>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Login</button>
            </div>
        <% end %>
    </div>
</div>

app/views/admin/show.html.erb
<div class="row">
    <div class="col-sm-12">
        <h1>Control Panel</h1>
        <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
    </div>
    <div class="col-sm-12">
        <h3>Student Summary:</h3>
        <h4>Overall Average: <%=@average%></h4>
        <div class="table-responsive">
            <table class="table table-bordered table-hover" id="t01">
                <thead class="thead-light">
                    <tr>
                        <th>UIN</th>
                        <th>Student Name</th>
                        <th>Section</th>
                        <th>Attempts</th>
                        <th>Score</th>
                        <th>Change Section</th>
                    </tr>
                </thead>
                <tbody>
                    <% @students.each do |student| %>
                      <tr>
                        <td><%= student.uin %></td>
                        <td><%= student.name %></td>
                        <td><%= student.section %></td>
                        <td><%= student.attempts %></td>
                        <td><%= student.score %></td>
                        <td><%= form_tag do %>
                            <%= select_tag 'section', options_for_select(@list_of_sections, @selected_section) %>
                            <%= submit_tag "Update", :name => "uin[#{student.uin}]", class: "btn btn-primary btn-sm"  %>
                            <% end %>
                        </td>
                      </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-sm-12 margin-bottom">
        <h3>Question Summary:</h3>
        <div class="table-responsive">
            <table class="table table-bordered table-hover" id="t01">
                <thead class="thead-light">
                    <tr>
                        <th>ID</th>
                        <th>Difficulty</th>
                        <th>Content</th>
                        <th>Choice 1 Count</th>
                        <th>Choice 2 Count</th>
                        <th>Choice 3 Count</th>
                        <th>Choice 4 Count</th>
                        <th>Choice 5 Count</th>
                    </tr>
                </thead>
                <tbody>
                    <% @all_questions.each do |question| %>
                        <tr>
                            <td><%= question.qid %></td>
                            <td><%= question.difficulty %></td>
                            <td><%= question.content.truncate(500)  %></td>
                            <td><%= question.c1_count %></td>
                            <td><%= question.c2_count %></td>
                            <td><%= question.c3_count %></td>
                            <td><%= question.c4_count %></td>
                            <td><%= question.c5_count %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-sm-12 margin-bottom">
        <div class="form-group" style="margin: 20px 0px">
            <a href="/admin/questions/show" class="btn btn-primary btn-lg margin-bottom" role="button">Questions Manager</a>
            <a href="/admin/evaluations" class="btn btn-primary btn-lg margin-bottom" role="button">Evaluations Manager</a>
            <a href="/admin/export" class="btn btn-primary btn-lg margin-bottom" role="button">Export Students to CSV</a>
        </div>
        <h3>Section Information:</h3>
        <div class="table-responsive">
            <table class="table table-bordered table-hover" id="t01">
                <thead class="thead-light">
                    <tr>
                        <th>Section</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @sections.each do |section| %>
                      <tr>
                        <td><%= section.section_number %></td>
                        <td><%= button_to "Delete", {action: "delete",  value: section.section_number}, {class: 'btn btn-primary btn-sm'} %></td>
                      </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <h4>Add a Section:</h4>
        <%= form_tag do%>
            <label for="section_number">Section Number:</label>
            <%= number_field_tag :section_number %>
            <button type="submit" class="btn btn-primary">Add</button>
        <% end %>
    </div>
    <div class="col-sm-12">
        <h3>Delete All Students:</h3>
        <%= form_tag do%>
            <p>Please type the following text in the text box to confirm deletion: </p>
            <h4>"I want to delete all students in the database, and I understand that once deleted, they are not recoverable."</h4>
            <div class="form-group">
                <label for="disclaimer">Disclaimer:</label>
                <%= text_field_tag :disclaimer %>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-danger">Reset Student Database</button>
            </div>
        <% end %>
    </div>
</div>